[2024-05-28T04:30:42.100+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T04:30:42.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_files_batch.download_and_upload_task_0 scheduled__2024-05-28T04:28:00+00:00 [queued]>
[2024-05-28T04:30:42.164+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_files_batch.download_and_upload_task_0 scheduled__2024-05-28T04:28:00+00:00 [queued]>
[2024-05-28T04:30:42.165+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-28T04:30:42.213+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_upload_task_0> on 2024-05-28 04:28:00+00:00
[2024-05-28T04:30:42.219+0000] {standard_task_runner.py:63} INFO - Started process 144 to run task
[2024-05-28T04:30:42.221+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'download_files_batch', 'download_and_upload_task_0', 'scheduled__2024-05-28T04:28:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/download-files_batch.py', '--cfg-path', '/tmp/tmp7tigd0lm']
[2024-05-28T04:30:42.223+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask download_and_upload_task_0
[2024-05-28T04:30:42.327+0000] {task_command.py:426} INFO - Running <TaskInstance: download_files_batch.download_and_upload_task_0 scheduled__2024-05-28T04:28:00+00:00 [running]> on host 7f87f2070cf0
[2024-05-28T04:30:42.536+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='download_files_batch' AIRFLOW_CTX_TASK_ID='download_and_upload_task_0' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T04:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T04:28:00+00:00'
[2024-05-28T04:30:42.537+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T04:30:42.558+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py:320 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-05-28T04:32:33.263+0000] {logging_mixin.py:188} INFO - File downloaded successfully from https://covid.ourworldindata.org/data/owid-covid-data.csv!
[2024-05-28T04:32:34.925+0000] {logging_mixin.py:188} INFO - File our-world-in-data-covid19.csv uploaded successfully to MinIO!
[2024-05-28T04:32:34.926+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T04:32:34.927+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T04:32:34.944+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=download_files_batch, task_id=download_and_upload_task_0, run_id=scheduled__2024-05-28T04:28:00+00:00, execution_date=20240528T042800, start_date=20240528T043042, end_date=20240528T043234
[2024-05-28T04:32:35.031+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T04:32:35.053+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T04:32:35.055+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
