[2024-05-28T04:53:09.486+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T04:53:09.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_files_batch.download_and_upload_task_0 scheduled__2024-05-28T04:34:00+00:00 [queued]>
[2024-05-28T04:53:09.582+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_files_batch.download_and_upload_task_0 scheduled__2024-05-28T04:34:00+00:00 [queued]>
[2024-05-28T04:53:09.583+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 2
[2024-05-28T04:53:09.638+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_upload_task_0> on 2024-05-28 04:34:00+00:00
[2024-05-28T04:53:09.645+0000] {standard_task_runner.py:63} INFO - Started process 89 to run task
[2024-05-28T04:53:09.648+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'download_files_batch', 'download_and_upload_task_0', 'scheduled__2024-05-28T04:34:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/download-files_batch.py', '--cfg-path', '/tmp/tmpf14j_na5']
[2024-05-28T04:53:09.651+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask download_and_upload_task_0
[2024-05-28T04:53:09.777+0000] {task_command.py:426} INFO - Running <TaskInstance: download_files_batch.download_and_upload_task_0 scheduled__2024-05-28T04:34:00+00:00 [running]> on host 7f87f2070cf0
[2024-05-28T04:53:09.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='download_files_batch' AIRFLOW_CTX_TASK_ID='download_and_upload_task_0' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T04:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T04:34:00+00:00'
[2024-05-28T04:53:09.986+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T04:53:10.035+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py:320 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-05-28T04:57:45.596+0000] {logging_mixin.py:188} INFO - Error downloading file from https://covid.ourworldindata.org/data/owid-covid-data.csv: <urlopen error retrieval incomplete: got only 102158078 out of 102459393 bytes>
[2024-05-28T04:57:47.049+0000] {logging_mixin.py:188} INFO - File our-world-in-data-covid19.csv uploaded successfully to MinIO!
[2024-05-28T04:57:47.049+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T04:57:47.050+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T04:57:47.064+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=download_files_batch, task_id=download_and_upload_task_0, run_id=scheduled__2024-05-28T04:34:00+00:00, execution_date=20240528T043400, start_date=20240528T045309, end_date=20240528T045747
[2024-05-28T04:57:47.125+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T04:57:47.149+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T04:57:47.151+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
